name: Release go-httpbin cli binaries

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release go-httpbin cli binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64/windows
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Release go-httpbin cli binaries
        uses: wangyoucao577/go-release-action@v1.23
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "cmd/go-httpbin/" # go build cmd/go-httpbin/main.go
          binary_name: "go-httpbin"
          ldflags: "-s -w"
          extra_files: LICENSE
          post_command: |
            echo "ASSET_PATH=$INPUT_PROJECT_PATH/$BUILD_ARTIFACTS_FOLDER/$RELEASE_ASSET_FILE" >> $GITHUB_ENV